final List<Map<String, dynamic>> manualPlayersData = [
  {
    "id": 2931,
    "fullName": "Michael Jordan",
    "team": "Chicago Bulls",
    "gamesPlayed": 82,
    "points": 28.74,
    "assists": 3.45,
    "rebounds": 5.79,
  },
  {
    "id": 115,
    "fullName": "Stephen Curry",
    "team": "Golden State Warriors",
    "gamesPlayed": 69,
    "points": 27.26,
    "assists": 5.23,
    "rebounds": 5.35,
  },
  {
    "id": 237,
    "fullName": "LeBron James",
    "team": "Los Angeles Lakers",
    "gamesPlayed": 55,
    "points": 27.36,
    "assists": 8.25,
    "rebounds": 8.45,
  },
  {
    "id": 401,
    "fullName": "Derrick Rose",
    "team": "New York Knicks",
    "gamesPlayed": 51,
    "points": 17.98,
    "assists": 4.31,
    "rebounds": 2.75,
  },
  {
    "id": 140,
    "fullName": "Kevin Durant",
    "team": "Phoenix Suns",
    "gamesPlayed": 78,
    "points": 25.99,
    "assists": 5.86,
    "rebounds": 6.37,
  },
  {
    "id": 367,
    "fullName": "Chris Paul",
    "team": "Phoenix Suns",
    "gamesPlayed": 58,
    "points": 15.62,
    "assists": 8.16,
    "rebounds": 4.57,
  },
  {
    "id": 2933,
    "fullName": "Scottie Pippen",
    "team": "Chicago Bulls",
    "gamesPlayed": 44,
    "points": 19.11,
    "assists": 5.77,
    "rebounds": 5.16,
  },
  // Adicione outros jogadores aqui com seus respectivos IDs
];
