final List<Map<String, dynamic>> manualTeamsData = [
  {
    "id": 1,
    "abbreviation": "ATL",
    "city": "Atlanta",
    "conference": "East",
    "division": "Southeast",
    "full_name": "Atlanta Hawks",
  },
  {
    "id": 2,
    "abbreviation": "BOS",
    "city": "Boston",
    "conference": "East",
    "division": "Atlantic",
    "full_name": "Boston Celtics",
  },
  {
    "id": 3,
    "abbreviation": "BKN",
    "city": "Brooklyn",
    "conference": "East",
    "division": "Atlantic",
    "full_name": "Brooklyn Nets",
  },
  {
    "id": 4,
    "abbreviation": "CHA",
    "city": "Charlotte",
    "conference": "East",
    "division": "Southeast",
    "full_name": "Charlotte Hornets",
  },
  {
    "id": 5,
    "abbreviation": "CHI",
    "city": "Chicago",
    "conference": "East",
    "division": "Central",
    "full_name": "Chicago Bulls",
  },
  {
    "id": 6,
    "abbreviation": "CLE",
    "city": "Cleveland",
    "conference": "East",
    "division": "Central",
    "full_name": "Cleveland Cavaliers",
  },
  {
    "id": 7,
    "abbreviation": "DAL",
    "city": "Dallas",
    "conference": "West",
    "division": "Southwest",
    "full_name": "Dallas Mavericks",
  },
  {
    "id": 8,
    "abbreviation": "DEN",
    "city": "Denver",
    "conference": "West",
    "division": "Northwest",
    "full_name": "Denver Nuggets",
  },
  {
    "id": 9,
    "abbreviation": "DET",
    "city": "Detroit",
    "conference": "East",
    "division": "Central",
    "full_name": "Detroit Pistons",
  },
  {
    "id": 10,
    "abbreviation": "GSW",
    "city": "Golden State",
    "conference": "West",
    "division": "Pacific",
    "full_name": "Golden State Warriors",
  },
  {
    "id": 11,
    "abbreviation": "HOU",
    "city": "Houston",
    "conference": "West",
    "division": "Southwest",
    "full_name": "Houston Rockets",
  },
  {
    "id": 12,
    "abbreviation": "IND",
    "city": "Indiana",
    "conference": "East",
    "division": "Central",
    "full_name": "Indiana Pacers",
  },
  {
    "id": 13,
    "abbreviation": "LAC",
    "city": "LA",
    "conference": "West",
    "division": "Pacific",
    "full_name": "LA Clippers",
  },
  {
    "id": 14,
    "abbreviation": "LAL",
    "city": "Los Angeles",
    "conference": "West",
    "division": "Pacific",
    "full_name": "Los Angeles Lakers",
  },
  {
    "id": 15,
    "abbreviation": "MEM",
    "city": "Memphis",
    "conference": "West",
    "division": "Southwest",
    "full_name": "Memphis Grizzlies",
  },
  {
    "id": 16,
    "abbreviation": "MIA",
    "city": "Miami",
    "conference": "East",
    "division": "Southeast",
    "full_name": "Miami Heat",
  },
  {
    "id": 17,
    "abbreviation": "MIL",
    "city": "Milwaukee",
    "conference": "East",
    "division": "Central",
    "full_name": "Milwaukee Bucks",
  },
  {
    "id": 18,
    "abbreviation": "MIN",
    "city": "Minnesota",
    "conference": "West",
    "division": "Northwest",
    "full_name": "Minnesota Timberwolves",
  },
  {
    "id": 19,
    "abbreviation": "NOP",
    "city": "New Orleans",
    "conference": "West",
    "division": "Southwest",
    "full_name": "New Orleans Pelicans",
  },
  {
    "id": 20,
    "abbreviation": "NYK",
    "city": "New York",
    "conference": "East",
    "division": "Atlantic",
    "full_name": "New York Knicks",
  },
  {
    "id": 21,
    "abbreviation": "OKC",
    "city": "Oklahoma City",
    "conference": "West",
    "division": "Northwest",
    "full_name": "Oklahoma City Thunder",
  },
  {
    "id": 22,
    "abbreviation": "ORL",
    "city": "Orlando",
    "conference": "East",
    "division": "Southeast",
    "full_name": "Orlando Magic",
  },
  {
    "id": 23,
    "abbreviation": "PHI",
    "city": "Philadelphia",
    "conference": "East",
    "division": "Atlantic",
    "full_name": "Philadelphia 76ers",
  },
  {
    "id": 24,
    "abbreviation": "PHX",
    "city": "Phoenix",
    "conference": "West",
    "division": "Pacific",
    "full_name": "Phoenix Suns",
  },
  {
    "id": 25,
    "abbreviation": "POR",
    "city": "Portland",
    "conference": "West",
    "division": "Northwest",
    "full_name": "Portland Trail Blazers",
  },
  {
    "id": 26,
    "abbreviation": "SAC",
    "city": "Sacramento",
    "conference": "West",
    "division": "Pacific",
    "full_name": "Sacramento Kings",
  },
  {
    "id": 27,
    "abbreviation": "SAS",
    "city": "San Antonio",
    "conference": "West",
    "division": "Southwest",
    "full_name": "San Antonio Spurs",
  },
  {
    "id": 28,
    "abbreviation": "TOR",
    "city": "Toronto",
    "conference": "East",
    "division": "Atlantic",
    "full_name": "Toronto Raptors",
  },
  {
    "id": 29,
    "abbreviation": "UTA",
    "city": "Utah",
    "conference": "West",
    "division": "Northwest",
    "full_name": "Utah Jazz",
  },
  {
    "id": 30,
    "abbreviation": "WAS",
    "city": "Washington",
    "conference": "East",
    "division": "Southeast",
    "full_name": "Washington Wizards",
  },
];
